#!/usr/bin/tclsh

# Copyright 2003-2005 Interactive Motion Technologies, Inc.
# Cambridge, MA, USA
# http://www.interactive-motion.com
# All rights reserved

# starts 

global ob

set ob(crobhome) $::env(CROB_HOME)

global ob

source $ob(crobhome)/shm.tcl

puts "loading linux kernel module."
# run after mon
# start_lkm
start_shm

wshm sin_period 2.0
wshm sin_amplitude 0.1
wshm ao8_thandle 1
wshm ao8_tchannel 0

puts "sine controller, sin_period 2.0, sin_amplitude 0.1, handle 1, channel 0"
puts "hold on, hit enter to start"
gets stdin

start_loop

# infinite loop
movebox 0 6 {0 1 0} {0.0 0.0 0.0 0.0} {0.0 0.0 0.0 0.0}

puts "hit enter to stop"
gets stdin

# puts "unloading linux kernel module"
stop_loop
stop_shm
# stop_lkm

