INSTALL_DIR = ~/crob/tools
INSTALL_COMPONENTS = 1d 1sec.tcl ABOUT abox acenter all2a ankle anref anscales avmz beep.tcl c calib can.tcl cb cbackup cbackup.050126 cbackup.ok cbackup.old center checkdat cp2zip curl.tcl curs damp.tcl datbody datbody.old dathead datinfo display dolog doutsq ecal flicker ftcal ftsec ftvsmotors getadc getftbias getftbias.c gpan.tcl gplot gppl.tcl grabcal isaencal kickcal lical loopfix looptest lsboards lsrt mon motor_static motor.tcl motor_tests motor_tests_2 mousegames mousegames_es.help mousegames.help move msdev.tcl mvbox.tcl ogp omvbox.tcl owcenter plref raw.sh roadtrip robotestmenu runmg scales sendtdir shake sim sine sinesweep strepl ta.sh U.tcl vget wbox wcal wcenter wrefloop wrscales zeromotors zero.tcl

# notes tools varlist
install:
	mkdir -p $(INSTALL_DIR)
	for i in $(INSTALL_COMPONENTS); do install $$i $(INSTALL_DIR); done
