#ifndef CONTROL_DEFINITIONS_H
#define CONTROL_DEFINITIONS_H

#define CONTROLLER_INVALID_HANDLE NULL

#define CONTROL_PASS_INTERVAL 0.005

typedef void* Controller;

enum ControlState { CONTROL_OFFSET, CONTROL_CALIBRATION, CONTROL_OPTIMIZATION, CONTROL_OPERATION, CONTROL_PHASES_NUMBER };

// Control used values enumeration
enum ControlVariable { CONTROL_POSITION, CONTROL_VELOCITY, CONTROL_FORCE, CONTROL_ACCELERATION, CONTROL_MODES_NUMBER,
                       CONTROL_STIFFNESS = CONTROL_MODES_NUMBER, CONTROL_DAMPING, CONTROL_VARS_NUMBER };

typedef double ControlVariablesList[ CONTROL_VARS_NUMBER ];

#endif // CONTROL_DEFINITIONS_H
