#ifndef SHM_EMG_CONTROL_H
#define SHM_EMG_CONTROL_H

#include "shm_joint_control.h"

enum { SHM_EMG_OFFSET = SHM_JOINT_BYTE_END, SHM_EMG_CALIBRATION, SHM_EMG_SAMPLING, SHM_EMG_MEASUREMENT, SHM_EMG_BYTE_END };

#endif // SHM_EMG_CONTROL_H
