#ifndef SHM_JOINT_CONTROL_H
#define SHM_JOINT_CONTROL_H

enum { SHM_JOINT_POSITION, SHM_JOINT_FORCE, SHM_JOINT_STIFFNESS,
       SHM_JOINT_EMG_1, SHM_JOINT_EMG_2, SHM_JOINT_EMG_3, SHM_JOINT_EMG_4, SHM_JOINT_EMG_5, SHM_JOINT_FLOATS_NUMBER };

#define JOINT_DATA_BLOCK_SIZE SHM_JOINT_FLOATS_NUMBER * sizeof(float)

enum { SHM_ROBOT_DISABLE = 1, SHM_ROBOT_DISABLED = SHM_ROBOT_DISABLE, 
       SHM_ROBOT_ENABLE, SHM_ROBOT_ENABLED = SHM_ROBOT_ENABLE, 
       SHM_JOINT_RESET, SHM_JOINT_ERROR = SHM_JOINT_RESET, 
       SHM_JOINT_MEASURE, SHM_JOINT_MEASUREMENT = SHM_JOINT_MEASURE, 
       SHM_JOINT_OFFSET, SHM_JOINT_CALIBRATE, SHM_JOINT_CALIBRATION = SHM_JOINT_CALIBRATE, 
       SHM_JOINT_SAMPLE, SHM_JOINT_SAMPLING = SHM_JOINT_SAMPLE, SHM_JOINT_BYTE_END };

#endif // SHM_JOINT_CONTROL_H
