#ifndef SHM_ROBOT_CONTROL_H
#define SHM_ROBOT_CONTROL_H

enum { SHM_ROBOT_DISABLE = 1, SHM_ROBOT_DISABLED = SHM_ROBOT_DISABLE, 
       SHM_ROBOT_ENABLE, SHM_ROBOT_ENABLED = SHM_ROBOT_ENABLE, 
       SHM_ROBOT_RESET, SHM_ROBOT_ERROR = SHM_ROBOT_RESET, 
       SHM_ROBOT_OPERATE, SHM_ROBOT_OPERATING = SHM_ROBOT_OPERATE, 
       SHM_ROBOT_OFFSET, SHM_ROBOT_OFFSETTING = SHM_ROBOT_OFFSET,
       SHM_ROBOT_CALIBRATE, SHM_ROBOT_CALIBRATING = SHM_ROBOT_CALIBRATE, 
       SHM_ROBOT_OPTIMIZE, SHM_ROBOT_OPTIMIZING = SHM_ROBOT_OPTIMIZE, 
       SHM_ROBOT_SET_USER, SHM_ROBOT_SET_CONFIG,
       SHM_ROBOT_BYTE_END };

#endif // SHM_JOINT_CONTROL_H
