#ifndef SHM_JOINT_CONTROL_H
#define SHM_JOINT_CONTROL_H

#include "shm_axis_control.h"

enum { SHM_JOINT_POSITION, SHM_JOINT_FORCE, SHM_JOINT_STIFFNESS, SHM_JOINT_FLOATS_NUMBER };

enum { SHM_JOINTS_LIST = SHM_AXIS_BYTE_END, 
       SHM_ROBOT_DISABLE, SHM_ROBOT_DISABLED = SHM_ROBOT_DISABLE, 
       SHM_ROBOT_ENABLE, SHM_ROBOT_ENABLED = SHM_ROBOT_ENABLE, 
       SHM_JOINT_RESET, SHM_JOINT_ERROR = SHM_JOINT_RESET, 
       SHM_JOINT_OFFSET, SHM_JOINT_CALIBRATE, SHM_JOINT_BYTE_END };

#endif // SHM_JOINT_CONTROL_H
