#ifndef SHM_AXIS_CONTROL_H
#define SHM_AXIS_CONTROL_H

enum { SHM_AXIS_POSITION, SHM_AXIS_VELOCITY, SHM_AXIS_ACCELERATION, SHM_AXIS_FORCE, 
       SHM_AXIS_STIFFNESS, SHM_AXIS_DAMPING, SHM_AXIS_TIME, SHM_AXIS_FLOATS_NUMBER };

#define AXIS_DATA_BLOCK_SIZE SHM_AXIS_FLOATS_NUMBER * sizeof(float)

#endif // SHM_AXIS_CONTROL_H
