#ifndef SHM_AXIS_CONTROL_H
#define SHM_AXIS_CONTROL_H

//const char* SHM_AXIS_BASE_KEY = "axis_controls";

enum { SHM_AXIS_POSITION, SHM_AXIS_VELOCITY, SHM_AXIS_FORCE, SHM_AXIS_STIFFNESS = SHM_AXIS_FORCE,
       SHM_AXIS_ACCELERATION, SHM_AXIS_DAMPING = SHM_AXIS_ACCELERATION, SHM_AXIS_TIME, SHM_AXIS_FLOATS_NUMBER };

enum { SHM_COMMAND_DISABLE = 1, SHM_STATE_DISABLED = SHM_COMMAND_DISABLE, SHM_COMMAND_ENABLE, 
       SHM_STATE_ENABLED = SHM_COMMAND_ENABLE, SHM_COMMAND_RESET, SHM_STATE_ERROR = SHM_COMMAND_RESET, SHM_COMMAND_CALIBRATE, SHM_AXIS_BYTE_END };

#endif // SHM_AXIS_CONTROL_H
